-- osm_data_08052026_2.sql — OpenStreetMap POI import for PanteeThai.com (batch 2)
-- Generated:  2026-05-08 13:20:37 UTC
-- Source:     OpenStreetMap contributors (ODbL)
--             https://www.openstreetmap.org/copyright
-- Script:     tools/osm_import.php
-- Categories: island, national_park, waterfall (retry), temple (retry), hotel (retry), attraction, historic
-- Provinces:  10 pilot provinces

SET NAMES utf8mb4;


-- ────────────────────────────────────────────────────────────
-- Koh Samui (samui)
-- ────────────────────────────────────────────────────────────
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'เกาะสมุย', 'Ko Samui', 'island', ST_GeomFromText('POINT(100.0013973 9.5011362)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'น้ำตกหน้าเมือง ชั้น 1', 'Namuang Waterfall - Level 1', 'waterfall', ST_GeomFromText('POINT(99.9840529 9.4665510)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Khun Si Waterfall', 'Khun Si Waterfall', 'waterfall', ST_GeomFromText('POINT(100.0140549 9.5217365)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'น้ำตกภูเขา', 'Mountain Waterfall', 'waterfall', ST_GeomFromText('POINT(99.9790004 9.5192402)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Secret waterfall', 'Secret waterfall', 'waterfall', ST_GeomFromText('POINT(99.9683715 9.5201561)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'น้ำตกหินลาด', 'Hin Lat Waterfall', 'waterfall', ST_GeomFromText('POINT(99.9670876 9.5212161)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Namuang 3 Waterfall', 'Namuang 3 Waterfall', 'waterfall', ST_GeomFromText('POINT(99.9894332 9.4706749)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'น้ำตกหน้าเมือง ชั้น 2', 'Namuang Waterfall - Level 2', 'waterfall', ST_GeomFromText('POINT(99.9900107 9.4721401)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'น้ำตกบางปอ', 'Bang Por waterfall', 'waterfall', ST_GeomFromText('POINT(99.9551825 9.5682968)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Tartan waterfall', 'Tartan waterfall', 'waterfall', ST_GeomFromText('POINT(99.9912049 9.5110670)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'na muang', 'na muang', 'waterfall', ST_GeomFromText('POINT(100.0080311 9.4615046)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Tan Rua', 'Tan Rua', 'waterfall', ST_GeomFromText('POINT(99.9925035 9.5350607)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'น้ำตกลาดขี้ลิง', 'Lardwanorn Waterfall', 'waterfall', ST_GeomFromText('POINT(99.9652279 9.5013508)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'waterfall', 'waterfall', 'waterfall', ST_GeomFromText('POINT(100.0075119 9.4626145)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Zong Raue', 'Zong Raue', 'waterfall', ST_GeomFromText('POINT(99.9605201 9.5458977)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Rotunda', 'Rotunda', 'temple', ST_GeomFromText('POINT(99.9982529 9.5707479)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'พระใหญ่ หรือ พระพุทธสันติทีปนาถ วัดพระใหญ่', 'Big Buddha', 'temple', ST_GeomFromText('POINT(100.0598016 9.5708299)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Bo Phut', 'Wat Bo Phut', 'temple', ST_GeomFromText('POINT(100.0323264 9.5558581)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Samret', 'Wat Samret', 'temple', ST_GeomFromText('POINT(100.0113295 9.4389300)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Praderm', 'Wat Praderm', 'temple', ST_GeomFromText('POINT(99.9922114 9.4444697)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Kiri Wongkaram', 'Wat Kiri Wongkaram', 'temple', ST_GeomFromText('POINT(99.9360546 9.4562328)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Chedi Khao Phut', 'Chedi Khao Phut', 'temple', ST_GeomFromText('POINT(99.9651093 9.4110544)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Phu Khao Thong (Gukauthong)', 'Wat Phu Khao Thong (Gukauthong)', 'temple', ST_GeomFromText('POINT(99.9956684 9.5655998)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Chinese Temple', 'Chinese Temple', 'temple', ST_GeomFromText('POINT(99.9980172 9.5703269)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Lamai', 'Wat Lamai', 'temple', ST_GeomFromText('POINT(100.0424729 9.4741447)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Laem Sor', 'Wat Laem Sor', 'temple', ST_GeomFromText('POINT(99.9704003 9.4137917)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Chedi Sila Ngu', 'Chedi Sila Ngu', 'temple', ST_GeomFromText('POINT(100.0311555 9.4507859)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Sila Ngu', 'Wat Sila Ngu', 'temple', ST_GeomFromText('POINT(100.0308318 9.4512666)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Buddha Footprint', 'Buddha Footprint', 'temple', ST_GeomFromText('POINT(100.0038874 9.4314408)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'เจดีย์​วัดเขาหัวจุก', 'Pagoda Khao Hua Jook', 'temple', ST_GeomFromText('POINT(100.0588521 9.5371439)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Khirimat', 'Wat Khirimat', 'temple', ST_GeomFromText('POINT(99.9406764 9.4250039)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Sitting buddha', 'Sitting buddha', 'temple', ST_GeomFromText('POINT(99.9165012 9.5738677)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Chedi Laem Sor', 'Chedi Laem Sor', 'temple', ST_GeomFromText('POINT(99.9689857 9.4117083)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Na Phra Lan', 'Wat Na Phra Lan', 'temple', ST_GeomFromText('POINT(99.9842826 9.5825430)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'วัดคุณาราม', 'Wat Khunaram', 'temple', ST_GeomFromText('POINT(100.0006049 9.4498162)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Plai Laem', 'Wat Plai Laem', 'temple', ST_GeomFromText('POINT(100.0671230 9.5715293)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'วัดสมุรทราราม', 'Wat Samuthra Ram', 'temple', ST_GeomFromText('POINT(99.9362181 9.5097267)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'วัดน้ำตกหินลาด', 'Wat Hin Lat', 'temple', ST_GeomFromText('POINT(99.9560338 9.5212504)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'วัดคงคาราม', 'Wat Khongkharam', 'temple', ST_GeomFromText('POINT(99.9377059 9.5301886)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Wat Chaweng', 'Wat Chaweng', 'temple', ST_GeomFromText('POINT(100.0451032 9.5310568)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Laem Din Priest\'s Camp Site', 'Laem Din Priest\'s Camp Site', 'temple', ST_GeomFromText('POINT(99.9331418 9.5164010)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Bill Resort', 'Bill Resort', 'hotel', ST_GeomFromText('POINT(100.0408758 9.4574773)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'The Imperial Samui', 'The Imperial Samui', 'hotel', ST_GeomFromText('POINT(100.0543461 9.5055958)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Tembo Beach Club & Resort', 'Tembo Beach Club & Resort', 'hotel', ST_GeomFromText('POINT(100.0534095 9.5569278)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Secret Garden', 'Secret Garden', 'hotel', ST_GeomFromText('POINT(100.0551346 9.5576512)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui Pier', 'Samui Pier', 'hotel', ST_GeomFromText('POINT(100.0562630 9.5585060)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Smile House', 'Smile House', 'hotel', ST_GeomFromText('POINT(100.0284623 9.5602515)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui Mermaid', 'Samui Mermaid', 'hotel', ST_GeomFromText('POINT(100.0596193 9.5608273)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Chaweng Cove Resotel', 'Chaweng Cove Resotel', 'hotel', ST_GeomFromText('POINT(100.0563360 9.5166710)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'The Kala', 'The Kala', 'hotel', ST_GeomFromText('POINT(100.0634388 9.4886822)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Coral Cove Resort', 'Coral Cove Resort', 'hotel', ST_GeomFromText('POINT(100.0610190 9.4906450)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Coral Cove Chalet', 'Coral Cove Chalet', 'hotel', ST_GeomFromText('POINT(100.0621146 9.4891574)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Beach Republic Hotel', 'Beach Republic Hotel', 'hotel', ST_GeomFromText('POINT(100.0621260 9.4724070)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Ban Sabai Sunset Resort', 'Ban Sabai Sunset Resort', 'hotel', ST_GeomFromText('POINT(99.9334980 9.4639140)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui Orchid Resort', 'Samui Orchid Resort', 'hotel', ST_GeomFromText('POINT(100.0168524 9.4303224)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Zazen Boutique Resort & Spa', 'Zazen Boutique Resort & Spa', 'hotel', ST_GeomFromText('POINT(100.0181522 9.5667744)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui World Resort', 'Samui World Resort', 'hotel', ST_GeomFromText('POINT(100.0181302 9.5648082)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'ShaSa Resort', 'ShaSa Resort', 'hotel', ST_GeomFromText('POINT(100.0097091 9.4208284)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Lipa Lovely Resort', 'Lipa Lovely Resort', 'hotel', ST_GeomFromText('POINT(99.9340929 9.4978801)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Lamai BayView Resort', 'Lamai BayView Resort', 'hotel', ST_GeomFromText('POINT(100.0650113 9.4709711)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Ark Bar Beach Resort 2', 'Ark Bar Beach Resort 2', 'hotel', ST_GeomFromText('POINT(100.0648527 9.5314719)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Ark Bar Beach Resort 3', 'Ark Bar Beach Resort 3', 'hotel', ST_GeomFromText('POINT(100.0646332 9.5313521)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Ark Bar Beach Resort 1', 'Ark Bar Beach Resort 1', 'hotel', ST_GeomFromText('POINT(100.0651234 9.5316014)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Jungle Club', 'Jungle Club', 'hotel', ST_GeomFromText('POINT(100.0471864 9.4998130)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Crystal Bay Resort', 'Crystal Bay Resort', 'hotel', ST_GeomFromText('POINT(100.0660537 9.4783578)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Hutcha Resort', 'Hutcha Resort', 'hotel', ST_GeomFromText('POINT(100.0036268 9.5683044)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Amari Palm Reef', 'Amari Palm Reef', 'hotel', ST_GeomFromText('POINT(100.0692640 9.5369220)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Baan Laem Sila Resort', 'Baan Laem Sila Resort', 'hotel', ST_GeomFromText('POINT(100.0625738 9.4857188)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui Mountain Village', 'Samui Mountain Village', 'hotel', ST_GeomFromText('POINT(100.0627237 9.4862616)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Sandalwood', 'Sandalwood', 'hotel', ST_GeomFromText('POINT(100.0632445 9.4858563)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'X2', 'X2', 'hotel', ST_GeomFromText('POINT(100.0193309 9.4339952)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Thongson Bay Bungalows', 'Thongson Bay Bungalows', 'hotel', ST_GeomFromText('POINT(100.0758712 9.5864585)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui Buri Beach Resort', 'Samui Buri Beach Resort', 'hotel', ST_GeomFromText('POINT(99.9852235 9.5804416)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Baan Phulay', 'Baan Phulay', 'hotel', ST_GeomFromText('POINT(99.9302544 9.4931388)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Kanok Buri Resort', 'Kanok Buri Resort', 'hotel', ST_GeomFromText('POINT(99.9331650 9.4961755)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Lipa Bay Resort', 'Lipa Bay Resort', 'hotel', ST_GeomFromText('POINT(99.9352142 9.5007265)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Nikki Beach Koh Samui', 'Nikki Beach Koh Samui', 'hotel', ST_GeomFromText('POINT(99.9349516 9.4994179)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Rajapruek Samui Resort', 'Rajapruek Samui Resort', 'hotel', ST_GeomFromText('POINT(99.9343339 9.4984147)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Santiburi Resort', 'Santiburi Resort', 'hotel', ST_GeomFromText('POINT(99.9919147 9.5724447)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Coconut Palm Beach Resort', 'Coconut Palm Beach Resort', 'hotel', ST_GeomFromText('POINT(100.0183421 9.5664628)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Fair House Villas & Spa, Koh Samui', 'Fair House Villas & Spa, Koh Samui', 'hotel', ST_GeomFromText('POINT(100.0154310 9.5724687)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Free House Bungalow', 'Free House Bungalow', 'hotel', ST_GeomFromText('POINT(100.0205735 9.5646405)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Adarin Beach Resort', 'Adarin Beach Resort', 'hotel', ST_GeomFromText('POINT(100.0082075 9.5695551)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Paradise Beach Resort', 'Paradise Beach Resort', 'hotel', ST_GeomFromText('POINT(100.0088360 9.5685350)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'PGS Hotel Sandy Bay Resort', 'PGS Hotel Sandy Bay Resort', 'hotel', ST_GeomFromText('POINT(100.0178698 9.5652499)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Peace Resort', 'Peace Resort', 'hotel', ST_GeomFromText('POINT(100.0225899 9.5625571)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui Palm Beach Resort & Royal Wing', 'Samui Palm Beach Resort & Royal Wing', 'hotel', ST_GeomFromText('POINT(100.0196746 9.5649283)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'The Fine Place', 'The Fine Place', 'hotel', ST_GeomFromText('POINT(100.0095296 9.5647601)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Bamboo Tropical Lounge', 'Bamboo Tropical Lounge', 'hotel', ST_GeomFromText('POINT(100.0094031 9.5655563)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'W Retreat Koh Samui', 'W Retreat Koh Samui', 'hotel', ST_GeomFromText('POINT(100.0170254 9.5731173)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Magic Garden', 'Tarnim & Magic Garden - Secret Buddha Garden', 'other', ST_GeomFromText('POINT(99.9948103 9.4826675)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'หินตาหินยาย', 'Hin Ta & Hin Yai (Grandma and Grandpa Rocks)', 'other', ST_GeomFromText('POINT(100.0390379 9.4518264)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Valentine Stone', 'Valentine Stone', 'other', ST_GeomFromText('POINT(100.0366886 9.4586920)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Namuang Safari Park', 'Namuang Safari Park', 'other', ST_GeomFromText('POINT(99.9881128 9.4667809)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui Elephant Sanctuary Bophut', 'Samui Elephant Sanctuary Bophut', 'other', ST_GeomFromText('POINT(100.0378218 9.5493189)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Butterfly Hill', 'Butterfly Hill', 'other', ST_GeomFromText('POINT(99.9662579 9.4678929)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Water slides', 'Water slides', 'other', ST_GeomFromText('POINT(99.9898727 9.4716801)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Sky Fox Zip Line', 'Sky Fox Zip Line', 'other', ST_GeomFromText('POINT(100.0053563 9.4634441)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Snorkel Spot', 'Snorkel Spot', 'other', ST_GeomFromText('POINT(100.0666499 9.4786555)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Giant Fruit Sculptures Durian Mangosteen', 'Giant Fruit Sculptures Durian Mangosteen', 'other', ST_GeomFromText('POINT(99.9956510 9.4781685)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Silver Beach', 'Silver Beach', 'other', ST_GeomFromText('POINT(100.0667231 9.4777047)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Fisherman\'s Village Bophut Walking Street', 'Fisherman\'s Village Bophut Walking Street', 'other', ST_GeomFromText('POINT(100.0315073 9.5589760)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Samui Elephant Home', 'Samui Elephant Home', 'other', ST_GeomFromText('POINT(100.0012574 9.4560732)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Monk Statue', 'Monk Statue', 'other', ST_GeomFromText('POINT(100.0313293 9.5560984)', 4326), 'osm', 'active');
INSERT IGNORE INTO places (province_slug, name_th, name_en, category, location, source, status) VALUES ('samui', 'Lingam Arch', 'Lingam Arch', 'other', ST_GeomFromText('POINT(100.0494401 9.4688571)', 4326), 'osm', 'active');

-- ────────────────────────────────────────────────────────────
-- Total rows inserted: 105
-- API errors:          0
-- ────────────────────────────────────────────────────────────
-- To import:  mysql -u USER -p DB_NAME < tools/osm_data_08052026_2.sql
